openapi: 3.0.0
info:
  title: 'Vigeogamesite API'
  version: '0.3'
servers:
  -
    url: 'http://vgsite/api'
paths:
  '/albums/{id}':
    get:
      description: 'An album'
      operationId: 'Vgsite\API\AlbumController::getOne'
      parameters:
        -
          $ref: '#/components/parameters/id'
        -
          $ref: '#/components/parameters/fields'
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/album'
        '404':
          description: 'Requested album not found'
  /albums:
    get:
      description: 'A list of albums'
      operationId: 'Vgsite\API\AlbumController::getAll'
      parameters:
        -
          $ref: '#/components/parameters/page'
        -
          $ref: '#/components/parameters/per_page'
        -
          $ref: '#/components/parameters/sort'
        -
          $ref: '#/components/parameters/fields'
        -
          $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/album'
  '/games/{id}':
    get:
      description: 'A game'
      operationId: 'Vgsite\API\GameController::getOne'
      parameters:
        -
          $ref: '#/components/parameters/id'
        -
          $ref: '#/components/parameters/fields'
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
        '404':
          description: 'Requested game not found'
  /games:
    get:
      description: 'A list of games'
      operationId: 'Vgsite\API\GameController::getAll'
      parameters:
        -
          $ref: '#/components/parameters/page'
        -
          $ref: '#/components/parameters/per_page'
        -
          $ref: '#/components/parameters/sort'
        -
          $ref: '#/components/parameters/fields'
        -
          $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
  /search:
    get:
      description: 'Search all the things'
      operationId: 'Vgsite\API\SearchController::getAll'
      parameters:
        -
          required: true
          minLength: 3
          $ref: '#/components/parameters/q'
        -
          $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: 'Things matching request query {q}'
          content:
            application/json:
              schema:
                properties:
                  title: { type: string }
                  title_sort: { type: string }
                  type: { type: string }
                  category: { type: string }
                  url: { type: string }
                type: object
  '/users/{id}':
    get:
      description: 'A user'
      operationId: 'Vgsite\API\UserController::getOne'
      parameters:
        -
          $ref: '#/components/parameters/id'
        -
          $ref: '#/components/parameters/fields'
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '404':
          description: 'Requested user not found'
  /users:
    get:
      description: 'A list of users'
      operationId: 'Vgsite\API\UserController::getAll'
      parameters:
        -
          $ref: '#/components/parameters/page'
        -
          $ref: '#/components/parameters/per_page'
        -
          $ref: '#/components/parameters/sort'
        -
          $ref: '#/components/parameters/fields'
        -
          $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
components:
  schemas:
    album:
      properties:
        id:
          type: string
        title:
          type: string
        subtitle:
          type: string
        keywords:
          type: boolean
        publisher:
          type: string
        cid:
          type: string
        albumid:
          type: string
        release:
          type: string
        price:
          type: string
        href:
          type: string
      type: object
    game:
      properties:
        id:
          type: string
        title:
          type: string
        genre:
          type: string
        platforms:
          type: array
          items:
            type: string
        release:
          type: string
          format: date
        href:
          type: string
      type: object
    user:
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        verified:
          type: boolean
        gender:
          type: string
        region:
          description: 'enum(''us'', ''jp'', ''eu'', ''au'')'
          type: string
        rank:
          type: string
        avatar:
          type: string
        timezone:
          type: string
        href:
          type: string
      type: object
  parameters:
    q:
      name: q
      in: query
      description: 'Search term'
      schema:
        type: string
    sort:
      name: sort
      in: query
      description: 'Custom sorted results. Format: `?sort=fieldname[:asc|desc]`'
      schema:
        type: string
      example: 'release:desc'
    fields:
      name: fields
      in: query
      description: 'A list of comma-separated fields to include in the response object.'
      schema:
        type: string
      example: 'title,release_date,tags'
    page:
      name: page
      in: query
      description: 'Page number'
      schema:
        type: integer
    per_page:
      name: per_page
      in: query
      description: 'Number of results per page'
      schema:
        type: integer
    id:
      name: id
      in: path
      description: 'The numeric ID for the requested item'
      required: true
      schema:
        type: integer
